name: Hashi
favicon: null
layout_spectrum: 0.60052
typography_spectrum: 0.02161
title: Hashi. Bridging Cultures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0000'
    - '#fca428'
    - '#63a3e0'
    - '#e91e21'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
