name: 'Monster '
favicon: null
layout_spectrum: 0.96333
typography_spectrum: 0.02161
title: Hashi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0000'
    - '#fca428'
    - '#63a3e0'
    - '#e91e21'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.7203111734706908
  rhythmicContrast: 0.1586262327618897
purpose: []
